products = [
    {
        '_id': '1',
        'name': 'Bourgogne',
        'image': '/images/1.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 19.99,
        'countInStock': 2,
        'rating': 2.5,
        'numReviews': 12,
    },

    {
        '_id': '2',
        'name': 'Bordeau',
        'image': '/images/2.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 12.00,
        'countInStock': 18,
        'rating': 0,
        'numReviews': 12,
    },

    {
        '_id': '12',
        'name': 'Cote du Rhone',
        'image': '/images/3.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 17.99,
        'countInStock': 12,
        'rating': 1,
        'numReviews': 12,
    },

    {
        '_id': '3',
        'name': 'Morgon',
        'image': '/images/3.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 13.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        '_id': '4',
        'name': 'Cote Rotie',
        'image': '/images/4.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 11.99,
        'countInStock': 20,
        'rating': 4,
        'numReviews': 12,
    },

    {
        '_id': '5',
        'name': 'Saint Emillion',
        'image': '/images/5.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 18.99,
        'countInStock': 10,
        'rating': 3.5,
        'numReviews': 12,
    },

    {
        '_id': '6',
        'name': 'Pinot Noir',
        'image': '/images/6.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 12.99,
        'countInStock': 14,
        'rating': 2.5,
        'numReviews': 12,
    },

    {
        '_id': '7',
        'name': 'Cote de Nuit',
        'image': '/images/7.png',
        'description': 'un bordeaux de très bonne qualité',
        'brand': 'lavieclaire',
        'category': 'vin bio',
        'price': 15.99,
        'countInStock': 1,
        'rating': 1.5,
        'numReviews': 12,
    },
]