# Generated by Django 4.0.2 on 2022-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoSite',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='imagePromo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
