# Generated by Django 4.0.2 on 2022-06-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_logosite_alter_carousel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='publiciteimage',
            name='emplacement',
        ),
    ]
