# Generated by Django 4.0.3 on 2022-03-31 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_order_rename_createat_product_createdat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdress',
            new_name='AdresseLivraison',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Commande',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemCommande',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Produits',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='Reactions',
        ),
    ]
