# Generated by Django 4.0.3 on 2022-03-31 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_rename_shippingadress_adresselivraison_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
        migrations.RenameModel(
            old_name='Reactions',
            new_name='Reaction',
        ),
    ]
