# Generated by Django 4.0.2 on 2022-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
