# Generated by Django 4.0.2 on 2022-05-03 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_reaction_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('favorite_createdAt', models.DateTimeField(blank=True, null=True)),
                ('favorite_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.produit')),
                ('user_favorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
