# Generated by Django 4.0.2 on 2022-06-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='category',
        ),
    ]
